### PR TITLE
feat: wine 5.0 and updated tools

### PR DESCRIPTION
**Pull request by jdehaan**
- MONO 4.9.4
- GECKO 2.47.1

### CODE REVIEW

**Comment by jdehaan** [comment]
Sorry for the noise this is not quite ready yet...

**Comment by jdehaan** [comment]
Tested works on initial run without volume setup correctly.

I took the liberty to align the version of the image to the version of wine. I think this is in the spirit of most images...

**Comment by scottyhardy** [comment]
Hi @jdehaan 

I'm looking to upgrade to using wine 5.0 but not quite ready yet.  I've also  got to get a contribution doco up and going to give a better guide on how I want to manage pull requests.

I'm keen to include any contributions though so first off, could you please change to a pull request to dev branch instead of master?  Also please remove the change the the version - I'll be using release branches to decide on version numbering depending on changes being introduced.

**Comment by jdehaan** [comment]
Hi @scottyhardy whatever you want, I needed to upgrade mainly for my private use. So I can adapt the PR, I am happy if that can be better maintained in a well known place.

**Pull request closed without merging**
